### ISSUE TITLE
ORN deployment for fragnet-search

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/fragnet#13]
Discussions at the ORN GA meeting concluded that it would be useful to deploy fragnet-search (not fragnet-deplict or fragnet-ui) as an ORN service.

Most of this would already be handled as part of the plans for an operator for fragnet deployment.
The extra work that would be needed is:

1. swagger descriptors for the API (quite simple to add)
2. ORN semantic annotations (probably simple but we'll need some help with this)
3. actually deploying to ORN prod site
4. exemplification e.g. using Jupyter

**Comment by tdudgeon** [comment]
ping @thomasexner

**Comment by thomasexner** [comment]
I can help with 2 and 4 even if we should decide how far we want to go with 2.

**Comment by alanbchristie** [comment]
Deployment to production site is complete (initial templates etc.) and file changes merged.

**Comment by alanbchristie** [comment]
The search has been deployed - I suspect this issue is now resolved
